In [1]:
!pip install pandas pycountry-convert

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: pycountry-convert in /opt/anaconda3/lib/python3.12/site-packages (0.7.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: pprintpp>=0.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.4.0)
Requirement already satisfied: pycountry>=16.11.27.1 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (24.6.1)
Requirement already satisfied: pytest>=3.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (7.4.4)
Requirement already satisfied: pytest-mock>=1.6.3 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (3.14.0)
Requirement already satisfied: pytest-cov>=2.5.1 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (6.0.0)
Requirement already satisfied: repoze.lru>=0.7 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.7)
Requirement already satisfied: wheel>=0.30.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.43.0)
Requirement already satisfied: iniconfig in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (1.1.1)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (23.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (1.0.0)
Requirement already satisfied: coverage>=7.5 in /opt/anaconda3/lib/python3.12/site-packages (from coverage[toml]>=7.5->pytest-cov>=2.5.1->pycountry-convert) (7.6.8)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
# imports
import pandas as pd
import warnings
import pycountry_convert as pc
warnings.filterwarnings("ignore", category=FutureWarning)

In [3]:
# Load the data
trade_data = pd.read_excel('../Original Data/TradeData.xlsx')

# View the data
trade_data.head(10)

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20170101,2017,52,2017,4,AFG,Afghanistan,X,...,0.000000e+00,False,0.000000e+00,False,NaN,4.354661e+07,4.354661e+07,0,False,True
1,C,A,20170101,2017,52,2017,4,AFG,Afghanistan,X,...,0.000000e+00,False,0.000000e+00,False,NaN,4.354661e+07,4.354661e+07,0,False,True
2,C,A,20170101,2017,52,2017,31,AZE,Azerbaijan,X,...,3.464400e+05,False,0.000000e+00,False,NaN,3.117960e+04,3.117960e+04,0,False,True
3,C,A,20170101,2017,52,2017,31,AZE,Azerbaijan,X,...,3.464400e+05,False,0.000000e+00,False,NaN,3.117960e+04,3.117960e+04,0,False,True
4,C,A,20170101,2017,52,2017,32,ARG,Argentina,X,...,3.071990e+06,False,NaN,False,NaN,5.133280e+05,5.133280e+05,0,False,True
5,C,A,20170101,2017,52,2017,32,ARG,Argentina,X,...,2.047800e+04,False,NaN,False,NaN,1.497612e+04,1.497612e+04,0,False,True
6,C,A,20170101,2017,52,2017,32,ARG,Argentina,X,...,3.049100e+06,False,NaN,False,NaN,4.947112e+05,4.947112e+05,0,False,True
7,C,A,20170101,2017,52,2017,32,ARG,Argentina,X,...,2.100000e+03,False,NaN,False,NaN,3.129000e+03,3.129000e+03,0,False,True
8,C,A,20170101,2017,52,2017,32,ARG,Argentina,X,...,3.120000e+02,False,NaN,False,NaN,5.116800e+02,5.116800e+02,0,False,True
9,C,A,20170101,2017,52,2017,36,AUS,Australia,X,...,3.730166e+11,False,3.736108e+11,False,NaN,4.380701e+10,4.380701e+10,0,False,True

In [4]:
trade_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20119 entries, 0 to 20118
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   typeCode                  20119 non-null  object
 1   freqCode                  20119 non-null  object
 2   refPeriodId               20119 non-null  int64
 3   refYear                   20119 non-null  int64
 4   refMonth                  20119 non-null  int64
 5   period                    20119 non-null  int64
 6   reporterCode              20119 non-null  int64
 7   reporterISO               20119 non-null  object
 8   reporterDesc              20119 non-null  object
 9   flowCode                  20119 non-null  object
 10  flowDesc                  20119 non-null  object
 11  partnerCode               20119 non-null  int64
 12  partnerISO                20119 non-null  object
 13  partnerDesc               20119 non-null  object
 14  partner2Code              20119 non-null  int64
 15  partner2ISO               20119 non-null  object
 16  partner2Desc              20119 non-null  object
 17  classificationCode        20119 non-null  object
 18  classificationSearchCode  20119 non-null  object
 19  isOriginalClassification  20119 non-null  bool
 20  cmdCode                   20119 non-null  int64
 21  cmdDesc                   20119 non-null  object
 22  aggrLevel                 20119 non-null  int64
 23  isLeaf                    20119 non-null  bool
 24  customsCode               20119 non-null  object
 25  customsDesc               20119 non-null  object
 26  mosCode                   20119 non-null  int64
 27  motCode                   20119 non-null  int64
 28  motDesc                   20119 non-null  object
 29  qtyUnitCode               20119 non-null  int64
 30  qtyUnitAbbr               19402 non-null  object
 31  qty                       20119 non-null  float64
 32  isQtyEstimated            20119 non-null  bool
 33  altQtyUnitCode            20119 non-null  int64
 34  altQtyUnitAbbr            16450 non-null  object
 35  altQty                    20119 non-null  float64
 36  isAltQtyEstimated         20119 non-null  bool
 37  netWgt                    19487 non-null  float64
 38  isNetWgtEstimated         20119 non-null  bool
 39  grossWgt                  18297 non-null  float64
 40  isGrossWgtEstimated       20119 non-null  bool
 41  cifvalue                  6088 non-null   float64
 42  fobvalue                  20119 non-null  float64
 43  primaryValue              20119 non-null  float64
 44  legacyEstimationFlag      20119 non-null  int64
 45  isReported                20119 non-null  bool
 46  isAggregate               20119 non-null  bool
dtypes: bool(8), float64(7), int64(14), object(18)
memory usage: 6.1+ MB

In [5]:
columns_to_keep = [
    'refYear', 'reporterDesc',
    'flowDesc', 'partnerDesc', 'cmdCode', 'qty',
    'primaryValue', 'reporterISO', 'partnerISO'
]

# New data frame with only the selected columns
trade_data = trade_data[columns_to_keep]

In [6]:
# changes the comodity codes into more readable format
trade_data['cmdCode'] = trade_data['cmdCode'].replace({2709: 'Oil', 2701: 'Coal', 271111: 'Gas'})

# checks the dataframe updated
print(trade_data.head(20))

    refYear reporterDesc flowDesc                       partnerDesc cmdCode  \
0      2017  Afghanistan   Export                             World    Coal
1      2017  Afghanistan   Export                          Pakistan    Coal
2      2017   Azerbaijan   Export                             World    Coal
3      2017   Azerbaijan   Export                           Georgia    Coal
4      2017    Argentina   Export                             World    Coal
5      2017    Argentina   Export  Bolivia (Plurinational State of)    Coal
6      2017    Argentina   Export                            Brazil    Coal
7      2017    Argentina   Export                             Chile    Coal
8      2017    Argentina   Export                           Uruguay    Coal
9      2017    Australia   Export                             World    Coal
10     2017    Australia   Export                         Argentina    Coal
11     2017    Australia   Export                           Austria    Coal
12     2017    Australia   Export                           Belgium    Coal
13     2017    Australia   Export                            Brazil    Coal
14     2017    Australia   Export                           Myanmar    Coal
15     2017    Australia   Export                             Chile    Coal
16     2017    Australia   Export                             China    Coal
17     2017    Australia   Export                            France    Coal
18     2017    Australia   Export                           Germany    Coal
19     2017    Australia   Export              China, Hong Kong SAR    Coal

             qty  primaryValue reporterISO partnerISO
0   0.000000e+00  4.354661e+07         AFG        W00
1   0.000000e+00  4.354661e+07         AFG        PAK
2   3.464400e+05  3.117960e+04         AZE        W00
3   3.464400e+05  3.117960e+04         AZE        GEO
4   3.071990e+06  5.133280e+05         ARG        W00
5   2.047800e+04  1.497612e+04         ARG        BOL
6   3.049100e+06  4.947112e+05         ARG        BRA
7   2.100000e+03  3.129000e+03         ARG        CHL
8   3.120000e+02  5.116800e+02         ARG        URY
9   3.730166e+11  4.380701e+10         AUS        W00
10  3.879500e+08  7.013163e+07         AUS        ARG
11  7.675000e+07  1.293528e+07         AUS        AUT
12  9.180980e+08  1.549954e+08         AUS        BEL
13  5.789218e+09  9.594981e+08         AUS        BRA
14  8.350267e+07  5.603450e+06         AUS        MMR
15  2.200987e+09  2.131570e+08         AUS        CHL
16  8.340690e+10  9.041861e+09         AUS        CHN
17  2.778822e+09  5.223554e+08         AUS        FRA
18  4.093640e+08  7.688363e+07         AUS        DEU
19  2.924920e+08  2.469487e+07         AUS        HKG

In [7]:
# Checks for percent of any missing values
percentage_missing = trade_data.isnull().sum() * 100 / len(trade_data)
missing_value_df = pd.DataFrame({'percent_missing': percentage_missing})

print(missing_value_df)

              percent_missing
refYear                   0.0
reporterDesc              0.0
flowDesc                  0.0
partnerDesc               0.0
cmdCode                   0.0
qty                       0.0
primaryValue              0.0
reporterISO               0.0
partnerISO                0.0

In [8]:
# Renames the columns
trade_data = trade_data.rename(columns={"refYear": "year", "reporterDesc": "exporter", "flowDesc": "flow", "partnerDesc": "importer", "cmdCode": "resource",
                    "qty": "weight (kg)", "primaryValue": "value (US$)", "reporterISO": "exporterISO", "partnerISO": "importerISO"})
# Check column names updated
trade_data.head()

,year,exporter,flow,importer,resource,weight (kg),value (US$),exporterISO,importerISO
0,2017,Afghanistan,Export,World,Coal,0.0,43546609.57,AFG,W00
1,2017,Afghanistan,Export,Pakistan,Coal,0.0,43546609.57,AFG,PAK
2,2017,Azerbaijan,Export,World,Coal,346440.0,31179.60,AZE,W00
3,2017,Azerbaijan,Export,Georgia,Coal,346440.0,31179.60,AZE,GEO
4,2017,Argentina,Export,World,Coal,3071990.0,513327.98,ARG,W00

In [9]:
# Code adapted from [https://stackoverflow.com/questions/55910004/get-continent-name-from-country-using-pycountry]
def country_to_continent(country_name):
    try:
        country_alpha2 = pc.country_name_to_country_alpha2(country_name)
        country_continent_code = pc.country_alpha2_to_continent_code(country_alpha2)
        country_continent_name = pc.convert_continent_code_to_continent_name(country_continent_code)
        return country_continent_name
    except (KeyError, AttributeError):
        return None


trade_data["exporter continent"] = trade_data['exporterISO'].apply(country_to_continent)
trade_data["importer continent"] = trade_data['importerISO'].apply(country_to_continent)

In [10]:
trade_data = trade_data.replace("Russian Federation", "Russia")

In [11]:
# checks for any missing values in partnerISO and reporterISO field
missing_partner = trade_data['importerISO'].isna().sum()
missing_reporter = trade_data['exporterISO'].isna().sum()
missing_continent_partner = trade_data['exporter continent'].isna().sum()
missing_continent_reporter = trade_data['importer continent'].isna().sum()
print(f"{missing_partner} for partnerISO")
print(f"{missing_reporter} for reporterISO")
print(f"{missing_continent_partner} for partner continent")
print(f"{missing_continent_reporter} for reporter continent")

0 for partnerISO
0 for reporterISO
97 for partner continent
2368 for reporter continent

In [12]:
missing_exporter_isos = trade_data[trade_data['exporter continent'].isna()]['exporter'].unique()
missing_importer_isos = trade_data[trade_data['importer continent'].isna()]['importer'].unique()
# prints the unique ISO codes with missing continents
print(f"ReporterISO with missing continents: {missing_exporter_isos}")

print(f"PartnerISO with missing continents: {missing_importer_isos}")

ReporterISO with missing continents: ['Other Asia, nes' 'Timor-Leste']
PartnerISO with missing continents: ['World' 'Other Asia, nes' 'Timor-Leste' 'Bunkers' 'Areas, nes'
 'Special Categories' 'Free Zones' 'Other Europe, nes' 'Antarctica'
 'Sint Maarten' 'Rest of America, nes' 'Pitcairn' 'Western Sahara'
 'United States Minor Outlying Islands' 'LAIA, nes' 'Other Africa, nes']

In [13]:

# keeps the rows where exporter and importer continent is not na
trade_data = trade_data[trade_data['exporter continent'].notna()]
trade_data = trade_data[trade_data['importer continent'].notna()]
missing_continent_partner = trade_data['exporter continent'].isna().sum()
missing_continent_reporter = trade_data['importer continent'].isna().sum()
print(f"{missing_continent_partner} for partner continent")
print(f"{missing_continent_reporter} for reporter continent")

0 for partner continent
0 for reporter continent

In [14]:
# Create and save new excel file with all data cleaning steps
#trade_data.to_csv('Trade Data Updated.csv', index=False)